//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KwickFitIntegration.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KwickFitIntegration.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;&gt;
        ///&lt;GEODS exp_cid=&quot;2JPK&quot;&gt;
        ///&lt;REQUEST type=&quot;RETURN&quot; subtype=&quot;CALLBUR&quot; EXP_ExperianRef=&quot;&quot; success=&quot;Y&quot; timestamp=&quot;Mon, 10 Mar 2014 at 11:17 AM&quot; id=&quot;2JPK&quot;&gt;
        ///&lt;MB45 seq=&quot;01&quot;&gt;
        ///&lt;VRM&gt;DK51JYP&lt;/VRM&gt;
        ///&lt;ENGINECAPACITY&gt;02500&lt;/ENGINECAPACITY&gt;
        ///&lt;MAKE&gt;LDV&lt;/MAKE&gt;
        ///&lt;MODEL&gt;CONVOY&lt;/MODEL&gt;
        ///&lt;COLOUR&gt;WHITE&lt;/COLOUR&gt;
        ///&lt;TRANSMISSION&gt;MANUAL 5 GEARS&lt;/TRANSMISSION&gt;
        ///&lt;DOORPLANLITERAL&gt;PANEL VAN&lt;/DOORPLANLITERAL&gt;
        ///&lt;TRANSMISSIONCODE&gt;M&lt;/TRANSMISSIONCODE&gt;
        ///&lt;NUMBEROFDRDS&gt;2&lt;/NUMBEROFDRDS&gt;
        ///&lt;DRDITEMS&gt;
        ///&lt;OP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dk51jypRequest {
            get {
                return ResourceManager.GetString("dk51jypRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;&gt;
        ///  &lt;GEODS exp_cid=&apos;dOqI&apos;&gt;
        ///    &lt;REQUEST type=&apos;RETURN&apos; subtype=&apos;CALLBUR&apos; EXP_ExperianRef=&apos;&apos; success=&apos;Y&apos; timestamp=&apos;Tue, 20 Aug 2013 at 3:34 PM&apos; id=&apos;dOqI&apos;&gt;
        ///      &lt;MB45 seq=&apos;01&apos;&gt;
        ///        &lt;VRM&gt;MT57XAJ &lt;/VRM&gt;
        ///        &lt;ENGINECAPACITY&gt;01910&lt;/ENGINECAPACITY&gt;
        ///        &lt;MAKE&gt;FIAT                &lt;/MAKE&gt;
        ///        &lt;MODEL&gt;BRAVO                                             &lt;/MODEL&gt;
        ///        &lt;COLOUR&gt;BLUE                &lt;/COLOUR&gt;
        ///        &lt;TRANSMISSION&gt;MANUAL 6 GEARS        &lt;/TRAN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidResponseTestData {
            get {
                return ResourceManager.GetString("ValidResponseTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DRDITEMS&gt;
        ///          &lt;OPTION&gt;1&lt;/OPTION&gt;
        ///          &lt;DRD&gt;12847&lt;/DRD&gt;
        ///          &lt;TYRESIZE&gt;205/55R16&lt;/TYRESIZE&gt;
        ///          &lt;LOADINDEX&gt;091&lt;/LOADINDEX&gt;
        ///          &lt;SPEEDINDEX&gt;V&lt;/SPEEDINDEX&gt;
        ///          &lt;TYREPRESSURE&gt;2.3&lt;/TYREPRESSURE&gt;
        ///          &lt;TYREPRESSUREREAR&gt;2.3&lt;/TYREPRESSUREREAR&gt;
        ///          &lt;RIMSIZE&gt;7x16&lt;/RIMSIZE&gt;
        ///          &lt;RIMOFFSET&gt;31&lt;/RIMOFFSET&gt;
        ///          &lt;NUTBOLTTORQUE&gt;90&lt;/NUTBOLTTORQUE&gt;
        ///          &lt;LADENTPFRONT&gt;2.6&lt;/LADENTPFRONT&gt;
        ///          &lt;LADENTPREAR&gt;2.6&lt;/LADENTPREAR&gt;
        ///          &lt;WTDRVIN&gt;198&lt;/W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidSingleTyre {
            get {
                return ResourceManager.GetString("ValidSingleTyre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DRDITEMS&gt;
        ///  &lt;OPTION&gt;1&lt;/OPTION&gt;
        ///  &lt;DRD&gt;14847&lt;/DRD&gt;
        ///  &lt;TYRESIZE&gt;205/70R16&lt;/TYRESIZE&gt;
        ///  &lt;LOADINDEX&gt;104&lt;/LOADINDEX&gt;
        ///  &lt;SPEEDINDEX&gt;S&lt;/SPEEDINDEX&gt;
        ///  &lt;RIMSIZE&gt;5.5x16&lt;/RIMSIZE&gt;
        ///  &lt;RIMOFFSET&gt;50&lt;/RIMOFFSET&gt;
        ///  &lt;NUTBOLTTORQUE&gt;160&lt;/NUTBOLTTORQUE&gt;
        ///&lt;/DRDITEMS&gt;.
        /// </summary>
        internal static string ValidSingleTyreNoPressures {
            get {
                return ResourceManager.GetString("ValidSingleTyreNoPressures", resourceCulture);
            }
        }
    }
}
